#!/usr/bin/env python

def set_options(opt):
  opt.tool_options('compiler_cxx')

def configure(conf):
  conf.check_tool('compiler_cxx')
  conf.check_tool('node_addon')

def build(bld):
  obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  obj.target = 'qt'
  obj.source = ['qt.cc', 'qapplication.cc', 'qwidget.cc', 'qsize.cc', 
                'qmouseevent.cc', 'qkeyevent.cc',
                'qtesteventlist.cc', 'qpixmap.cc',
                'qpainter.cc', 'qcolor.cc', 'qbrush.cc', 'qpen.cc',
                'qimage.cc', 'qpointf.cc', 'qpainterpath.cc', 'qfont.cc',
                'qmatrix.cc', 'qsound.cc', 'qscrollarea.cc', 'qscrollbar.cc']
  
  obj.includes = ['../deps/qt-4.8.0/darwin/x64/include','../deps/qt-4.8.0/darwin/x64/include/QtCore','../deps/qt-4.8.0/darwin/x64/include/QtGui','../deps/qt-4.8.0/darwin/x64/include/QtTest']
  obj.frameworkpath = ['../../deps/qt-4.8.0/darwin/x64/lib']
  obj.framework = ['QtCore','QtGui','QtTest']
  obj.linkflags = ['-static']
