#!/usr/bin/env python

def set_options(opt):
  opt.tool_options('compiler_cxx')

def configure(conf):
  conf.check_tool('compiler_cxx')
  conf.check_tool('node_addon')

def build(bld):
  obj = bld.new_task_gen('cxx', 'shlib', 'node_addon')
  obj.target = 'qt'
  obj.source = ['qt.cc', 'qapplication.cc', 'qwidget.cc', 'qsize.cc', 
                'qmouseevent.cc', 'qkeyevent.cc',
                'qtesteventlist.cc', 'qpixmap.cc',
                'qpainter.cc', 'qcolor.cc', 'qbrush.cc', 'qpen.cc',
                'qimage.cc', 'qpointf.cc', 'qpainterpath.cc', 'qfont.cc',
                'qmatrix.cc', 'qsound.cc', 'qscrollarea.cc', 'qscrollbar.cc']
  
  # Example of valid instantiated template - it will contain these lines:
  # obj.includes =  ['/usr/local/Cellar/qt/4.8.0/include', '/usr/local/Cellar/qt/4.8.0/include/QtCore', '/usr/local/Cellar/qt/4.8.0/include/QtGui', '/usr/local/Cellar/qt/4.8.0/include/QtTest']
  # obj.frameworkpath = ['/usr/local/Cellar/qt/4.8.0/lib']
  # obj.framework = ['QtCore', 'QtGui', 'QtTest']


  obj.includes = ['/usr/local/Cellar/qt/4.8.0/include','/usr/local/Cellar/qt/4.8.0/include/QtCore','/usr/local/Cellar/qt/4.8.0/include/QtGui','/usr/local/Cellar/qt/4.8.0/include/QtTest']
  obj.frameworkpath = ['/usr/local/Cellar/qt/4.8.0/lib']
  obj.framework = ['QtCore','QtGui','QtTest']
